// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfgL2iW-8XQux58aJzrSWb5NQaGiTiUk',
    appId: '1:901436566591:web:972a61ea2cdecccd29dc8a',
    messagingSenderId: '901436566591',
    projectId: 'fir-asif-taj-tutorials',
    authDomain: 'fir-asif-taj-tutorials.firebaseapp.com',
    storageBucket: 'fir-asif-taj-tutorials.appspot.com',
    measurementId: 'G-Y82RDS1ZM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqFvHcTE_4DVLCb6UHplFKQGu2ofrM8fs',
    appId: '1:901436566591:android:1cd3cbfd66c8862829dc8a',
    messagingSenderId: '901436566591',
    projectId: 'fir-asif-taj-tutorials',
    storageBucket: 'fir-asif-taj-tutorials.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUeAOPSQGiTKDYEMmXCsErNSahpDfxQAc',
    appId: '1:901436566591:ios:4dd6527c3c210b4729dc8a',
    messagingSenderId: '901436566591',
    projectId: 'fir-asif-taj-tutorials',
    storageBucket: 'fir-asif-taj-tutorials.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAsifTajTutorials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUeAOPSQGiTKDYEMmXCsErNSahpDfxQAc',
    appId: '1:901436566591:ios:cbe68f1a73b24c4129dc8a',
    messagingSenderId: '901436566591',
    projectId: 'fir-asif-taj-tutorials',
    storageBucket: 'fir-asif-taj-tutorials.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAsifTajTutorials.RunnerTests',
  );
}
